### ISSUE TITLE
Microsoft Edge

### ISSUE THREAD

**Issue by thelamer** [linuxserver/proot-apps#12]
Edge does not launch a window, the pid runs and everything but it does not render a window on the desktop. Need to determine what is going on here to publish it officially.

**Comment by vbap** [comment]
Was just about to raise this - I observe same behaviour.

**Comment by thelamer** [comment]
> Was just about to raise this - I observe same behaviour.

There are a series of tagged apps in this repo that are built, but not advertised in the readme or in the gui interface. Edge is one of them, if you get anything to work let me know. You can shell into the app with `proot -R $HOME/proot-apps/appyouaretesting bash` and install packages (no sudo needed) run bins etc. 
I suspect the sandbox and zygote that msedge uses is not compatible with being run inside of ptrace.
