### ISSUE TITLE
OBS Studio does not include Linux Browser

### ISSUE THREAD

**Issue by msinfo32github** [linuxserver/proot-apps#15]
- Installing ghcr.io/linuxserver/proot-apps:obs includes OBS from the Alpine package (as far as I can tell) but that does not include the OBS Linux Browser (often called a Browser Source)

This is using [linuxserver/docker-webtop](https://github.com/linuxserver/docker-webtop) which by default uses Alpine XFCE image.

From what I can tell, there does not seem to be an Alpine package which includes obs with a browser source.

This seems to leave two options:

- Use an [unofficial](https://github.com/bazukas/obs-linuxbrowser) (unmaintained, and seems to have an old version of embedded chromium) OBS plugin
- Compile OBS from source? See [here](https://github.com/obsproject/obs-studio/wiki/Build-Instructions-For-Linux) and building with `DENABLE_BROWSER=ON` to enable the Browser Source.

**Comment by thelamer** [comment]
It can be rebased to Debian pretty painlessly as well. I think this is most likely the best option.

**Comment by thelamer** [comment]
I want to pull from their PPA, but am waiting for a Noble release, this might sit for a bit.

**Comment by thelamer** [comment]
They published noble packages today, I rebased and tested the browser plugin. 
![obs-browser](https://github.com/user-attachments/assets/9142a98d-38d9-42c5-9ea9-968a1b65ebf0)

Just `proot-apps update obs`

Closing
