### ISSUE TITLE
request: please add Anki support

### ISSUE THREAD

**Issue by shahram7** [linuxserver/proot-apps#17]
Hi friends,
Thank you for your time and effort.
It would be great if can install anki client using proot-apps.
Wish you the best.
Best regards, shahram

**Comment by thelamer** [comment]
`proot-apps install anki`

This program is kind of a buggy mess, you need to enable legacy imports to import any deck and the button alignment makes it unusable in many cases. (cropped on the bottom)
I installed it locally as well with the same issues so it is not a proot thing, seems like the devs don't use the xcb renderer or Linux much.
It is in there for install but I will not be advertising it until someone that uses this and knows what is up can make this work better.  There are a bunch of memory errors in it as well `double free or corruption (out)` both local and in proot. 
Using software rendering improved it a bit, but that is another thing the user would need to know so they were not presented with what seems like a broken app.
