### ISSUE TITLE
Error running Nextcloud-pa: Shared library libOpenGL.so.0 issue

### ISSUE THREAD

**Issue by drdada** [linuxserver/proot-apps#19]
Hello,
Since the last update of nextcloud-pa, I'm experiencing an issue when running Nextcloud-pa via Webtop:latest. The following error occurs:
`/opt/nextcloud/AppRun.wrapped: error while loading shared libraries: libOpenGL.so.0: cannot open shared object file: No such file or directory
/config/.local/bin/proot-apps: line 185: kill: (902) - No such process`

**Steps to reproduce the issue :**
Update nextcloud-pa
Run Nextcloud-pa via Webtop

**Additional Information :**
nextcloud-pa latest version
Webtop latest version
Xvnc KasmVNC 1.2.0

**Comment by thelamer** [comment]
Is fixed now update the app, also see https://github.com/linuxserver/proot-apps/issues/16
It's not perfect but it works as it did before at least.
