### ISSUE TITLE
LibreOffice v24.8.X instead of v7.X.X

### ISSUE THREAD

**Issue by nanospearing** [linuxserver/proot-apps#20]
I was wondering if there was any plan on migrating to this version or if there are issues with it. I am willing to take a look and push and update if yall would like me to :3

**Comment by nanospearing** [comment]
> ... it is currently out of date ...
> 
> My inclination is to wait for Alpine 3.21, but am open to solutions that are comparable in size and have aarch64 compatibility.

Do you think it would be worth it to create two separate versions for the users to choose from? If so I can whip up a version that uses Debian as its backend instead. Once the package upgrades we can then just remove the Debian version.

**Comment by aptalca** [comment]
It might be easier to submit a PR to alpine repos

**Comment by nanospearing** [comment]
I can do that :3
