### ISSUE TITLE
Zotero on Webtop Ubuntu KDE doesnt have any icon

### ISSUE THREAD

**Issue by shahram7** [linuxserver/proot-apps#21]
Hi there,
thank you for your time and effort.
unfortunately zotero pa doesn't have any launcher icon after installing with proot-apps.
![image](https://github.com/user-attachments/assets/f8e4c4cc-dbad-412a-8d9a-df1906ea9357)
Best Regards, Shahram

**Comment by thelamer** [comment]
This has been fixed, if you update the icon will be added properly.
